### PR TITLE
Update for v23.06

### PR DESCRIPTION
**Pull request by fredroy**
Use only sofang packages

### CODE REVIEW

**Review by alxbilger — COMMENTED** [review]
Should you not update PluginExampleConfig.cmake.in as well?

**Comment by fredroy** [comment]
> can I merge it @fredroy ?

I suppose 😅

**Comment by alxbilger** [comment]
@fredroy I am just not sure about the variables `PLUGINEXAMPLE_HAVE_SOFA_GUI_QT` and `PLUGINEXAMPLE_HAVE_QT5_CORE` as I don't understand where they come from. Can you have a look? We must merge this PR this week!

**Comment by alxbilger** [comment]
Just a reminder @fredroy, otherwise we merge as is until any problem is raised.

**Comment by fredroy** [comment]
> @fredroy I am just not sure about the variables `PLUGINEXAMPLE_HAVE_SOFA_GUI_QT` and `PLUGINEXAMPLE_HAVE_QT5_CORE` as I don't understand where they come from. Can you have a look? We must merge this PR this week!

They come from sofa_find_package() macros.

**Pull request merged**
